USE clinic_db;

-- ─────────────────────────────────────────────
-- USERS
-- Passwords are bcrypt hashes of 'Password123'
-- Use these accounts to log in during testing
-- ─────────────────────────────────────────────
-- admin password : Admin@123
-- patient password : Password123
INSERT INTO users (user_name, user_email, user_password, user_role, user_phone) VALUES
('Admin Clinic',    'admin@clinic.com',   '$2b$10$PKvdYuDoWklvg//Uh5iLHOw0S48zNBNZ7ZR50qW2AOGl1IyG1dcW.', 'admin',   '0123456789'),
('Ahmad Razif',     'ahmad@email.com',    '$2b$10$XvXtRJ1FDJS3AJ9TR99wou.uLaeMCkt0iALjCI0EcE1kwGWSkTomy', 'patient', '0112345678'),
('Nurul Aisyah',    'nurul@email.com',    '$2b$10$XvXtRJ1FDJS3AJ9TR99wou.uLaeMCkt0iALjCI0EcE1kwGWSkTomy', 'patient', '0123456780'),
('Raj Kumar',       'raj@email.com',      '$2b$10$XvXtRJ1FDJS3AJ9TR99wou.uLaeMCkt0iALjCI0EcE1kwGWSkTomy', 'patient', '0134567890'),
('Mei Ling',        'meiling@email.com',  '$2b$10$XvXtRJ1FDJS3AJ9TR99wou.uLaeMCkt0iALjCI0EcE1kwGWSkTomy', 'patient', '0145678901'),
('Hafiz Zulkifli',  'hafiz@email.com',    '$2b$10$XvXtRJ1FDJS3AJ9TR99wou.uLaeMCkt0iALjCI0EcE1kwGWSkTomy', 'patient', '0156789012');

-- ─────────────────────────────────────────────
-- DOCTORS
-- Created/managed by admin only
-- ─────────────────────────────────────────────
INSERT INTO doctors (doctor_name, doctor_specialization, doctor_email, doctor_phone) VALUES
('Dr. Amirul Hakim',   'General Practice',  'amirul@clinic.com',  '0312345678'),
('Dr. Priya Nair',     'Cardiology',        'priya@clinic.com',   '0323456789'),
('Dr. Tan Wei Kang',   'Orthopaedics',      'weikang@clinic.com', '0334567890');

-- ─────────────────────────────────────────────
-- APPOINTMENTS
-- patient_id 2–6 = the 5 patients above
-- doctor_id  1–3 = the 3 doctors above
-- ─────────────────────────────────────────────
INSERT INTO appointments (patient_id, doctor_id, appointment_date, appointment_time, appointment_status) VALUES
(2, 1, '2026-05-20', '09:00:00', 'completed'),
(3, 2, '2026-05-21', '10:30:00', 'completed'),
(4, 1, '2026-05-22', '11:00:00', 'completed'),
(5, 3, '2026-05-26', '14:00:00', 'pending'),
(6, 2, '2026-05-27', '15:30:00', 'pending');

-- ─────────────────────────────────────────────
-- MEDICAL RECORDS
-- Only for completed appointments (IDs 1, 2, 3)
-- Pending appointments don't have records yet
-- ─────────────────────────────────────────────
INSERT INTO medical_records (appointment_id, mr_diagnosis, mr_treatment, mr_notes) VALUES
(1, 'Acute upper respiratory tract infection', 'Prescribed amoxicillin 500mg for 5 days and paracetamol for fever', 'Patient advised to rest and increase fluid intake. Follow up in 1 week if symptoms persist.'),
(2, 'Hypertension Stage 1',                   'Prescribed amlodipine 5mg once daily. Lifestyle modification advised.',       'Patient to monitor BP daily. Referred for ECG. Return in 2 weeks.'),
(3, 'Mild knee osteoarthritis (right)',        'Prescribed naproxen 250mg twice daily. Physiotherapy referral given.',         'X-ray shows mild joint space narrowing. Advised low impact exercise.');

-- ─────────────────────────────────────────────
-- AUDIT LOGS
-- These are normally auto-generated by the backend.
-- A few manual entries added to pre-populate the table
-- for demonstration purposes only.
-- ─────────────────────────────────────────────
INSERT INTO audit_logs (user_id, auditlogs_action, auditlogs_logtime, auditlogs_ipaddress) VALUES
(1, 'USER_REGISTER', '2026-05-19 08:00:00', '127.0.0.1'),
(2, 'USER_REGISTER', '2026-05-19 08:15:00', '192.168.1.10'),
(3, 'USER_REGISTER', '2026-05-19 08:30:00', '192.168.1.11'),
(4, 'USER_REGISTER', '2026-05-19 08:45:00', '192.168.1.12'),
(5, 'USER_REGISTER', '2026-05-19 09:00:00', '192.168.1.13'),
(6, 'USER_REGISTER', '2026-05-19 09:15:00', '192.168.1.14'),
(1, 'USER_LOGIN',    '2026-05-20 08:55:00', '127.0.0.1'),
(2, 'USER_LOGIN',    '2026-05-20 08:58:00', '192.168.1.10'),
(1, 'CREATE_APPOINTMENT_1', '2026-05-20 09:00:00', '127.0.0.1'),
(3, 'USER_LOGIN',    '2026-05-21 10:25:00', '192.168.1.11'),
(1, 'CREATE_APPOINTMENT_2', '2026-05-21 10:30:00', '127.0.0.1'),
(4, 'USER_LOGIN',    '2026-05-22 10:55:00', '192.168.1.12'),
(1, 'CREATE_APPOINTMENT_3', '2026-05-22 11:00:00', '127.0.0.1'),
(1, 'CREATE_MEDICAL_RECORD_1', '2026-05-20 09:30:00', '127.0.0.1'),
(1, 'CREATE_MEDICAL_RECORD_2', '2026-05-21 11:00:00', '127.0.0.1'),
(1, 'CREATE_MEDICAL_RECORD_3', '2026-05-22 11:45:00', '127.0.0.1');
